version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  tomcat:
    image: tomcat:9-jdk11-openjdk
    container_name: tomcat-container
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=testdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword

networks:
  mynetwork:
    driver: bridge

