apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
      - name: ocirsecret  # Move imagePullSecrets here, not inside containers
      containers:
      - name: tomcat-application
        image: bog.ocir.io/ocicustomeropshb/marius-devops:v4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DB_NAME
          value: "testdb"
        - name: DB_PORT
          value: "3306"
        - name: DB_HOST
          value: "mysql-svc"


